### ISSUE TITLE
Setup database integration

### ISSUE THREAD

**Issue by ijsKoud** [ijsKoud/appiecal#14]
# Tasks
- [ ] Add models
- [ ] Add repositories
- [ ] Add ERD to documentation

# Acceptation Criteria

## Documentation
- [ ] An ERD is available in the documentation
- [ ] The ERD defines the database structure and its relations

## Code
- [ ] The models defined in the ERD are available in the code base
- [ ] For every model a repository has been defined
